/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedChatCharacterIdRouteImport } from './routes/_authenticated/chat.$characterId'
import { Route as AuthenticatedAdminCharactersIndexRouteImport } from './routes/_authenticated/admin/characters/index'
import { Route as AuthenticatedAdminCharactersIdRouteImport } from './routes/_authenticated/admin/characters/$id'
import { Route as AuthenticatedAdminCharactersNewRouteImport } from './routes/_authenticated/admin/characters/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedChatCharacterIdRoute =
  AuthenticatedChatCharacterIdRouteImport.update({
    id: '/chat/$characterId',
    path: '/chat/$characterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCharactersIndexRoute =
  AuthenticatedAdminCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCharactersIdRoute =
  AuthenticatedAdminCharactersIdRouteImport.update({
    id: '/characters/$id',
    path: '/characters/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCharactersNewRoute =
  AuthenticatedAdminCharactersNewRouteImport.update({
    id: '/characters/new',
    path: '/characters/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/characters': typeof CharactersRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/chat/$characterId': typeof AuthenticatedChatCharacterIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/characters/$id': typeof AuthenticatedAdminCharactersIdRoute
  '/admin/characters/new': typeof AuthenticatedAdminCharactersNewRoute
  '/admin/characters/': typeof AuthenticatedAdminCharactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/characters': typeof CharactersRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/chat/$characterId': typeof AuthenticatedChatCharacterIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/characters/$id': typeof AuthenticatedAdminCharactersIdRoute
  '/admin/characters/new': typeof AuthenticatedAdminCharactersNewRoute
  '/admin/characters': typeof AuthenticatedAdminCharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/characters': typeof CharactersRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/chat/$characterId': typeof AuthenticatedChatCharacterIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/characters/$id': typeof AuthenticatedAdminCharactersIdRoute
  '/_authenticated/admin/characters/new': typeof AuthenticatedAdminCharactersNewRoute
  '/_authenticated/admin/characters/': typeof AuthenticatedAdminCharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/characters'
    | '/pricing'
    | '/admin'
    | '/dashboard'
    | '/chat/$characterId'
    | '/admin/'
    | '/admin/characters/$id'
    | '/admin/characters/new'
    | '/admin/characters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/characters'
    | '/pricing'
    | '/dashboard'
    | '/chat/$characterId'
    | '/admin'
    | '/admin/characters/$id'
    | '/admin/characters/new'
    | '/admin/characters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/characters'
    | '/pricing'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/chat/$characterId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/characters/$id'
    | '/_authenticated/admin/characters/new'
    | '/_authenticated/admin/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CharactersRoute: typeof CharactersRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/chat/$characterId': {
      id: '/_authenticated/chat/$characterId'
      path: '/chat/$characterId'
      fullPath: '/chat/$characterId'
      preLoaderRoute: typeof AuthenticatedChatCharacterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/characters/': {
      id: '/_authenticated/admin/characters/'
      path: '/characters'
      fullPath: '/admin/characters/'
      preLoaderRoute: typeof AuthenticatedAdminCharactersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/characters/$id': {
      id: '/_authenticated/admin/characters/$id'
      path: '/characters/$id'
      fullPath: '/admin/characters/$id'
      preLoaderRoute: typeof AuthenticatedAdminCharactersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/characters/new': {
      id: '/_authenticated/admin/characters/new'
      path: '/characters/new'
      fullPath: '/admin/characters/new'
      preLoaderRoute: typeof AuthenticatedAdminCharactersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCharactersIdRoute: typeof AuthenticatedAdminCharactersIdRoute
  AuthenticatedAdminCharactersNewRoute: typeof AuthenticatedAdminCharactersNewRoute
  AuthenticatedAdminCharactersIndexRoute: typeof AuthenticatedAdminCharactersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCharactersIdRoute: AuthenticatedAdminCharactersIdRoute,
  AuthenticatedAdminCharactersNewRoute: AuthenticatedAdminCharactersNewRoute,
  AuthenticatedAdminCharactersIndexRoute:
    AuthenticatedAdminCharactersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedChatCharacterIdRoute: typeof AuthenticatedChatCharacterIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedChatCharacterIdRoute: AuthenticatedChatCharacterIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CharactersRoute: CharactersRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
