/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ChatCharacterIdRouteImport } from './routes/chat.$characterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCharacterIdRoute = ChatCharacterIdRouteImport.update({
  id: '/chat/$characterId',
  path: '/chat/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/chat/$characterId': typeof ChatCharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/chat/$characterId': typeof ChatCharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/chat/$characterId': typeof ChatCharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/characters' | '/dashboard' | '/pricing' | '/chat/$characterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characters' | '/dashboard' | '/pricing' | '/chat/$characterId'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/dashboard'
    | '/pricing'
    | '/chat/$characterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  ChatCharacterIdRoute: typeof ChatCharacterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$characterId': {
      id: '/chat/$characterId'
      path: '/chat/$characterId'
      fullPath: '/chat/$characterId'
      preLoaderRoute: typeof ChatCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  ChatCharacterIdRoute: ChatCharacterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
